# -*- coding: utf-8 -*-
"""GrumpGPT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QioiYMCWq_KXaL1iFF5l7CIvdEn326N6

#Pip installs
"""

# !pip install -qU langchain openai
# !pip install -qU huggingface_hub
# !pip install ngrok
# !pip install Flask==2.0.3
# !pip install pyngrok
# !pip install flask_ngrok

"""#Imports and Keys"""

import os

from langchain import PromptTemplate, HuggingFaceHub, LLMChain
from langchain.llms import OpenAI

os.environ['HUGGINGFACEHUB_API_TOKEN'] = '<HuggingFace Key>'
os.environ['OPENAI_API_KEY'] = '<OPENAI KEY>'

"""# Ngrok Auth Tokens

run only one of these
"""

"""#HuggingFace and Langchain"""

# initialize HF LLM
flan_t5 = HuggingFaceHub(
    repo_id="google/flan-t5-xl",
    model_kwargs={"temperature":0.2}
)

davinci = OpenAI(model_name='text-davinci-003')

# build prompt template for simple question-answering
# template = """
# I want you to act as an actor who is practicing being very angry for his role. 

# Here are some examples of good angry phrases to incorporate: 
# - you fool!
# - you silly!

# The result should sound very angry and should be 2 sentences long.

# Can you answer {question}?

# Answer: """

template = """
  Can you answer {question} in an angry voice?
"""
prompt = PromptTemplate(template=template, input_variables=["question"])

llm_chain = LLMChain(
    prompt=prompt,
    llm=flan_t5
)

# question = input("")
# text = llm_chain.run(question)
# print(text)

"""#Flask App"""

from flask import Flask, request
from flask_ngrok import run_with_ngrok
# from flask_cors import CORS

app = Flask(__name__)
# CORS(app)
run_with_ngrok(app)

@app.route('/', methods=['GET'])
def hello():
  return "this is a get response"

@app.route('/', methods=['POST'])
def answer_question():
    data = request.data
    print(data)
    question = "Ask? " + str(data)
    text = llm_chain.run(question)
    print(text)
    return text

@app.after_request
def add_cors_headers(response):
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, DELETE'
    response.headers['Access-Control-Allow-Headers'] = 'Content-Type'
    return response
    
if __name__ == '__main__':
    app.run()
